// Smdn.Extensions.Mtp.LiquidTestReports.dll (Smdn.Extensions.Mtp.LiquidTestReports-1.0.0-rc)
//   Name: Smdn.Extensions.Mtp.LiquidTestReports
//   AssemblyVersion: 1.0.0.0
//   InformationalVersion: 1.0.0-rc+ea0c00285802607e87ae06650cecedb2517c0956
//   TargetFramework: .NETCoreApp,Version=v10.0
//   Configuration: Release
//   Referenced assemblies:
//     DotLiquid, Version=2.3.197.0, Culture=neutral, PublicKeyToken=82e46016ecf9f07c
//     LiquidTestReports.Core, Version=2.0.0.0, Culture=neutral
//     Microsoft.Testing.Extensions.TrxReport, Version=2.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     Microsoft.Testing.Platform, Version=2.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Collections, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.ComponentModel, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Console, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Linq, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Memory, Version=10.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
//     System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Threading, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Xml.ReaderWriter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Xml.XmlSerializer, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
#nullable enable annotations

using Microsoft.Testing.Platform.Builder;

namespace Smdn.Extensions.Mtp.LiquidTestReports {
  public static class LiquidTestReportsExtensions {
    public static void AddLiquidTestReportsProvider(this ITestApplicationBuilder builder) {}
  }

  public static class TestingPlatformBuilderHook {
    public static void AddExtensions(ITestApplicationBuilder testApplicationBuilder, string[] arguments) {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.7.0.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.5.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
