// Smdn.Extensions.Mtp.LiquidTestReports.dll (Smdn.Extensions.Mtp.LiquidTestReports-1.1.0-preview1)
//   Name: Smdn.Extensions.Mtp.LiquidTestReports
//   AssemblyVersion: 1.1.0.0
//   InformationalVersion: 1.1.0-preview1+cc43db51173ab3806183db3aa2f88415c5f7dabd
//   TargetFramework: .NETStandard,Version=v2.0
//   Configuration: Release
//   Metadata: RepositoryUrl=https://github.com/smdn/Smdn.Extensions.Mtp.LiquidTestReports
//   Metadata: Microsoft.Testing.Platform.Application=true
//   Metadata: RepositoryBranch=main
//   Metadata: RepositoryCommit=cc43db51173ab3806183db3aa2f88415c5f7dabd
//   Referenced assemblies:
//     DotLiquid, Version=2.3.197.0, Culture=neutral, PublicKeyToken=82e46016ecf9f07c
//     LiquidTestReports.Core, Version=1.0.0.0, Culture=neutral
//     Microsoft.Testing.Extensions.TrxReport, Version=2.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     Microsoft.Testing.Platform, Version=2.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
#nullable enable annotations

using Microsoft.Testing.Platform.Builder;

namespace Smdn.Extensions.Mtp.LiquidTestReports {
  public static class LiquidTestReportsExtensions {
    public static void AddLiquidTestReportsProvider(this ITestApplicationBuilder builder) {}
  }

  public static class TestingPlatformBuilderHook {
    public static void AddExtensions(ITestApplicationBuilder testApplicationBuilder, string[] arguments) {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.8.0.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.6.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
