// Smdn.Extensions.Mtp.LiquidTestReports.dll (Smdn.Extensions.Mtp.LiquidTestReports-1.0.0-preview1)
//   Name: Smdn.Extensions.Mtp.LiquidTestReports
//   AssemblyVersion: 1.0.0.0
//   InformationalVersion: 1.0.0-preview1+4e162232f731d5781eb508686276793b8d35e1cf
//   TargetFramework: .NETCoreApp,Version=v8.0
//   Configuration: Release
//   Referenced assemblies:
//     DotLiquid, Version=2.3.197.0, Culture=neutral, PublicKeyToken=82e46016ecf9f07c
//     LiquidTestReports.Core, Version=2.0.0.0, Culture=neutral
//     Microsoft.Testing.Extensions.TrxReport, Version=2.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     Microsoft.Testing.Platform, Version=2.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Collections, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.ComponentModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Console, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Linq, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Xml.ReaderWriter, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Xml.XmlSerializer, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
#nullable enable annotations

using Microsoft.Testing.Platform.Builder;

public static class ExtensionInfo {
  public const string Description = "The MTP extension to convert TRX files generated during the test session into the preferred format using LiquidTestReports.";
  public const string DisplayName = "LiquidTestReports test report converter";
  public const string SemVer = "1.0.0-preview1";
}

namespace Smdn.Extensions.Mtp.LiquidTestReports {
  public static class LiquidTestReportsExtensions {
    public static void AddLiquidTestReportsProvider(this ITestApplicationBuilder builder) {}
  }

  public static class TestingPlatformBuilderHook {
    public static void AddExtensions(ITestApplicationBuilder testApplicationBuilder, string[] arguments) {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.7.0.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.5.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
