// SPDX-FileCopyrightText: 2025 smdn <smdn@smdn.jp>
// SPDX-License-Identifier: MIT
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

using Microsoft.Testing.Platform.CommandLine;
using Microsoft.Testing.Platform.Extensions;
using Microsoft.Testing.Platform.Extensions.CommandLine;

namespace Smdn.Extensions.Mtp.LiquidTestReports;

internal sealed class LiquidTestReportsGeneratorCommandLine : ICommandLineOptionsProvider {
  // cSpell:ignore liquidtr
  private const string LiquidTestReportsOptionNameCommonPrefix = "liquidtr-";
  public const string LiquidTestReportsTemplateFilePathOptionName = $"{LiquidTestReportsOptionNameCommonPrefix}template";
  public const string LiquidTestReportsOutputFileExtensionOptionName = $"{LiquidTestReportsOptionNameCommonPrefix}output-extension";
  public const string LiquidTestReportsParameterOptionName = $"{LiquidTestReportsOptionNameCommonPrefix}parameter";

  /// <inheritdoc />
  public string Uid => nameof(LiquidTestReportsGeneratorCommandLine);

  /// <inheritdoc />
  public string Version => global::ExtensionInfo.SemVer;

  /// <inheritdoc />
  public string DisplayName { get; } = global::ExtensionInfo.DisplayName;

  /// <inheritdoc />
  public string Description { get; } = global::ExtensionInfo.Description;

  /// <inheritdoc />
  public Task<bool> IsEnabledAsync() => Task.FromResult(true);

  public IReadOnlyCollection<CommandLineOption> GetCommandLineOptions()
    => [
      new(
        name: LiquidTestReportsTemplateFilePathOptionName,
        description: "Specify the template file used by LiquidTestReports and enable conversion from TRX test reports. To enable this feature, make sure to also specify the 'report-trx' option. LiquidTestReports will not generate anything unless a TRX file is generate.",
        arity: ArgumentArity.ExactlyOne,
        isHidden: false
      ),
      new(
        name: LiquidTestReportsOutputFileExtensionOptionName,
        description: "Specify the file extension for the output file of the conversion results generated by LiquidTestReports. If omitted, the same extension as the template file is used. The leading period of the extension can be omitted.",
        arity: ArgumentArity.ZeroOrOne,
        isHidden: false
      ),
      new(
        name: LiquidTestReportsParameterOptionName,
        description: "Specify parameters to pass to LiquidTestReports in the format `<name>=<value>`. Within the template file, the specified value can be referenced as `parameters.<name>`.",
        arity: ArgumentArity.ZeroOrMore,
        isHidden: false
      ),
    ];


  public Task<ValidationResult> ValidateCommandLineOptionsAsync(ICommandLineOptions commandLineOptions)
    => ValidationResult.ValidTask;

  public Task<ValidationResult> ValidateOptionArgumentsAsync(CommandLineOption commandOption, string[] arguments)
  {
    switch (commandOption.Name) {
      case LiquidTestReportsTemplateFilePathOptionName:
        if (!File.Exists(arguments[0]))
          return ValidationResult.InvalidTask($"Specified template file '{arguments[0]}' does not exist.");
        break;

      case LiquidTestReportsParameterOptionName:
        foreach (var argument in arguments) {
          var indexOfSeparator =
#if SYSTEM_STRING_INDEXOF_CHAR_STRINGCOMPARISON
            argument.IndexOf('=', StringComparison.Ordinal);
#else
            argument.IndexOf('=');
#endif

          if (indexOfSeparator < 1)
            return ValidationResult.InvalidTask($"'{argument}' is an invalid format. Parameters passed to LiquidTestReports must be in the format '<name>=<value>'.");
        }

        break;
    }

    return ValidationResult.ValidTask;
  }
}
